//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.22 at 10:01:14 PM CET 
//


package edu.uoc.pfc.formwork.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoApartado complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoApartado">
 *   &lt;complexContent>
 *     &lt;extension base="{}TipoComponente">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element ref="{}etiqueta"/>
 *           &lt;element ref="{}partida"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="contenido" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tipo" type="{}TipoTipoApartado" />
 *       &lt;attribute name="titulo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoApartado", propOrder = {
    "etiquetaOrPartida"
})
public class TipoApartado
    extends TipoComponente
{

    @XmlElements({
        @XmlElement(name = "etiqueta", type = TipoEtiqueta.class),
        @XmlElement(name = "partida", type = TipoPartida.class)
    })
    protected List<TipoComponente> etiquetaOrPartida;
    @XmlAttribute(name = "contenido")
    protected String contenido;
    @XmlAttribute(name = "tipo")
    protected TipoTipoApartado tipo;
    @XmlAttribute(name = "titulo")
    protected String titulo;

    /**
     * Gets the value of the etiquetaOrPartida property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the etiquetaOrPartida property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEtiquetaOrPartida().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoEtiqueta }
     * {@link TipoPartida }
     * 
     * 
     */
    public List<TipoComponente> getEtiquetaOrPartida() {
        if (etiquetaOrPartida == null) {
            etiquetaOrPartida = new ArrayList<TipoComponente>();
        }
        return this.etiquetaOrPartida;
    }

    /**
     * Gets the value of the contenido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContenido() {
        return contenido;
    }

    /**
     * Sets the value of the contenido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContenido(String value) {
        this.contenido = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTipoApartado }
     *     
     */
    public TipoTipoApartado getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTipoApartado }
     *     
     */
    public void setTipo(TipoTipoApartado value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the titulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitulo() {
        return titulo;
    }

    /**
     * Sets the value of the titulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitulo(String value) {
        this.titulo = value;
    }

}
