//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.10 at 09:20:43 PM CET 
//


package edu.uoc.pfc.formwork.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoTipoPartida.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipoTipoPartida">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="cantidad"/>
 *     &lt;enumeration value="cantidadNegativa"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipoTipoPartida")
@XmlEnum
public enum TipoTipoPartida {

    @XmlEnumValue("cantidad")
    CANTIDAD("cantidad"),
    @XmlEnumValue("cantidadNegativa")
    CANTIDAD_NEGATIVA("cantidadNegativa");
    private final String value;

    TipoTipoPartida(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipoTipoPartida fromValue(String v) {
        for (TipoTipoPartida c: TipoTipoPartida.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
