//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 11:22:43 PM CET 
//


package edu.uoc.pfc.formwork.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoFormulario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoFormulario">
 *   &lt;complexContent>
 *     &lt;extension base="{}TipoComponente">
 *       &lt;sequence>
 *         &lt;element name="titulo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;element ref="{}apartado"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="controlador" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoFormulario", propOrder = {
    "titulo",
    "descripcion",
    "apartado"
})
public class TipoFormulario
    extends TipoComponente
{

    @XmlElement(required = true)
    protected String titulo;
    @XmlElement(required = true)
    protected String descripcion;
    @XmlElement(required = true)
    protected List<TipoApartado> apartado;
    @XmlAttribute(name = "controlador", required = true)
    protected String controlador;

    /**
     * Gets the value of the titulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitulo() {
        return titulo;
    }

    /**
     * Sets the value of the titulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitulo(String value) {
        this.titulo = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

    /**
     * Gets the value of the apartado property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the apartado property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApartado().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoApartado }
     * 
     * 
     */
    public List<TipoApartado> getApartado() {
        if (apartado == null) {
            apartado = new ArrayList<TipoApartado>();
        }
        return this.apartado;
    }

    /**
     * Gets the value of the controlador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlador() {
        return controlador;
    }

    /**
     * Sets the value of the controlador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlador(String value) {
        this.controlador = value;
    }

}
