//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.10 at 09:20:43 PM CET 
//


package edu.uoc.pfc.formwork.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoApartado complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoApartado">
 *   &lt;complexContent>
 *     &lt;extension base="{}TipoComponente">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}partida"/>
 *       &lt;/sequence>
 *       &lt;attribute name="contenido" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="tipo" type="{}TipoTipoApartado" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoApartado", propOrder = {
    "partida"
})
public class TipoApartado
    extends TipoComponente
{

    protected List<TipoPartida> partida;
    @XmlAttribute(name = "contenido")
    @XmlSchemaType(name = "anySimpleType")
    protected String contenido;
    @XmlAttribute(name = "tipo")
    protected TipoTipoApartado tipo;

    /**
     * Gets the value of the partida property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partida property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartida().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoPartida }
     * 
     * 
     */
    public List<TipoPartida> getPartida() {
        if (partida == null) {
            partida = new ArrayList<TipoPartida>();
        }
        return this.partida;
    }

    /**
     * Gets the value of the contenido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContenido() {
        return contenido;
    }

    /**
     * Sets the value of the contenido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContenido(String value) {
        this.contenido = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTipoApartado }
     *     
     */
    public TipoTipoApartado getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTipoApartado }
     *     
     */
    public void setTipo(TipoTipoApartado value) {
        this.tipo = value;
    }

}
