//created on: 09-nov-2012
package formworktest.rules


//list any import classes here.
import edu.uoc.pfc.formwork.ui.Partida
import edu.uoc.pfc.formwork.ui.PartidaCantidad
import edu.uoc.pfc.formwork.ui.Formulario;
import java.math.BigDecimal;
import java.util.List;
import edu.uoc.pfc.formwork.service.Mensaje; 
import edu.uoc.pfc.formwork.service.Mensaje.TipoMensaje; 

// funciones
import function edu.uoc.pfc.formworktest.helper.Validaciones.isNifNie;
import function edu.uoc.pfc.formworktest.helper.Validaciones.formatNif;

//declare any global variables here
global Formulario theForm;
global List partidasAfectadas;
global List errores;

rule "initial-rule"
	salience 15
	no-loop 
	when
		Partida();
	then
		partidasAfectadas.clear();
		errores.clear();
end

rule "nif-error"
	salience 10
	when
		$p : Partida((id == "nif" || id == "nifr"), $v:value, !isNifNie(value))
	then
		Mensaje $m = new Mensaje(Mensaje.TipoMensaje.ERROR, "Nif incorrecto: " + $v, $p.getId());
		errores.add($m);
end

rule "nif-ok"
	salience 10
	no-loop
    when
        $p : Partida((id == "nif" || id == "nifr"), $v:value, isNifNie(value))
    then
		$p.setValue(formatNif((String)$v));
		partidasAfectadas.add($p);
end


rule "Partidas"
	salience 10
    when
	    $p : Partida(id == "p01" || id == "p02" || id == "p03" || id == "p04")
    then
	    BigDecimal $val1 = (BigDecimal)theForm.getPartida("p01").getValue();
    	BigDecimal $val2 = (BigDecimal)theForm.getPartida("p02").getValue();
    	BigDecimal $val3 = (BigDecimal)theForm.getPartida("p03").getValue();
    	BigDecimal $val4 = (BigDecimal)theForm.getPartida("p04").getValue();
    	
    	PartidaCantidad $p5 = (PartidaCantidad) theForm.getPartida("p05");
    	PartidaCantidad $i = (PartidaCantidad) theForm.getPartida("imp");
    	
    	BigDecimal $porcentaje =  new BigDecimal("0.01");

    	$p5.setValue( $val1.multiply($val2).multiply($porcentaje).add($val3.multiply($val4).multiply($porcentaje)));
    	$i.setValue($p5.getValue());
    	partidasAfectadas.add($p);
        partidasAfectadas.add($p5);
        partidasAfectadas.add($i);
end
